//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Projetc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyApplication
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string education { get; set; }
        public Nullable<int> jid { get; set; }
        public string Experience { get; set; }
        public string status { get; set; }
        public string resume { get; set; }
    }
}
