//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Projetc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_JobportalEntities : DbContext
    {
        public MVC_JobportalEntities()
            : base("name=MVC_JobportalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admintable> Admintables { get; set; }
        public virtual DbSet<ApplyApplication> ApplyApplications { get; set; }
        public virtual DbSet<photo> photos { get; set; }
    }
}
